controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

song_list:
    path: /song
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\SongController::list
